### ISSUE TITLE
Sélecteurs optimisés 

### ISSUE THREAD

**Issue by antoine-pous** [Lcfvs/PHPDOM#2]
Salut,

je viens de voir les modifications, et de les essayer, et franchement j'adhère pas avec ton système :/

Pour moi, si tu veux que ta lib soit optimisée tu dois avoir un système de sélecteurs simplifiés avec une gestion native des cas de création/suppression de noeuds/attributs ect...

Petit exemple:

``` PHP
// Créer un élément ou changer son contenu
$this->body->p = 'test';

// Détruire un élément
$this->body->p = null;

// Définir une liste d'attributs (créé l’élément si il n'existe pas)
$this->body->p->setAttr(['id' => 'test', 'class' => ['class1','class2'], 'data-test' => 'test']);

// Supprimer un attribut de l'élément
$this->body->p->setAttr(['data-test' => null]);

// Supprimer class1 en conservant class2
// Peut prendre un array en paramètre, si aucun paramètre supprime toutes les classes
$this->body->p->removeClass('class2');
```

**Comment by Lcfvs** [comment]
Concernant la création à la volée, je suis contre... cela nuirait à la relecture/compréhension du code d'autant plus que cela n'est possible que si tu n'as qu'un seul élément de ce type.

Pour le setAttr, tu as déjà `$element->setAttributes(array $attributes)`.

Sinon, pour un addClass et removeClass, c'est une bonne idée. ;)

**Comment by Lcfvs** [comment]
Done
